### ISSUE TITLE
Demon Output 

### ISSUE THREAD

**Issue by Zuriich** [lmb-freiburg/demon#22]
I'm using Demon to compare it with other Depthmaps and I have some trouble with the units of the output of Demon. Could you tell me in which units is Demon operating?

**Comment by harishannavajjala** [comment]
They are calculating inverse of depth i.,e 1/d in the depth map that is outputted. And I believe its in metres.

**Comment by sampepose** [comment]
Also note that the predicted inverse depth matches the unit translation.

**Comment by benjaminum** [comment]
As @sampepose says, the depth matches the unit translation.
Therefore, the depth does not have a unit.

**Comment by Zuriich** [comment]
Okay, well now I was applying the inverse of depth and I got another question:  which type of preprocessing you have applied to the data before the training? (normalization, max and min value of this, etc).

**Comment by FranciscoGomez90** [comment]
I also have the same question. I got to work the system but I don't know what the values are. Meters? Inches? Are they normalized? Pleas throw some light on this matter!

**Comment by edcross** [comment]
I was seeing the evaluation.py file and there appear three different ways of normalization (abs, log and inv). Which have you use to obtain the model you released?

**Comment by benjaminum** [comment]
In general it is not possible to infer absolute scale values from any number of images.
Because of this we trained our network to predict a unit translation vector.
This means the translation length is always 1.

The scale of the depth values correspond to this unit vector and thus don't have a unit.
To recover actual depth values in meters it is necessary to know the length of the translation vector in meters.

Assuming you know this length (camera baseline) B in meters you can compute the depth as

```
B * 1/D
```
with D as the inverse depth returned by the network.

@Zuriich During training we scale the depth values and the motion such that the camera baseline is 1. There is no other normalization.

@edcross The abs, log and inv you see in the evaluation.py are ways of optimally scaling the depth values. This was meant for a comparison with other methods that do not compute a camera motion but infer scale. In the end we only used the scale invariant metric, which does not need this.

**Comment by globalcaos** [comment]
Hello @benjaminum. I am using this thread since my question is related. Let me know if you want me to open a new thread.

I am trying to make sense of the optical flow that is coming out of the iterative_net, and I have noticed that all the values are always between -1 and 1. This does not seem right to me. I was expecting something from -10 and 10 maybe. Also, from the two components in the result['predict_depth2'], which one is x (horizontal) and which one is y (vertical)?

**Comment by sampepose** [comment]
The optical flow is normalized wrt the image dimensions. Multiply each directional channel x,y by the image width,height to get "true" optical flow.

Depth has 1 channel. Optical flow has 2 channels, first is x and second is y.

Sam Pepose

**Comment by benjaminum** [comment]
I think all questions here have been answered.

Thanks to everyone!
