### ISSUE TITLE
Was data augmentation necessary?

### ISSUE THREAD

**Issue by thbupt** [lmb-freiburg/demon#4]
Did you do any data augmentation (DA) for training DeMoN just as FlowNet2? It seems a little difficult to performe DA because of different kinds of inputs, such as flow, warped image and depth. If you did DA, could you give me some advice about how to perform DA for DeMoN?

**Comment by benjaminum** [comment]
We did geometric data augmentation i.e. mirroring images. We are limited to this type of transformation because augmentation must not change the internal camera parameters. We assume that the principal point is the image center.

We just ported our data op to tensorflow, which implements the augmentation; see the ```multivih5datareaderop``` dir.

I hope this information helps you.

**Comment by thbupt** [comment]
@benjaminum Thanks very much.
